import type { Metadata } from "next";

import "../styles/globals.scss";
import "@/src/styles/reset.css"
import Layout from "../components/layout/Layout";


export const metadata:Metadata = {
  title: {
    "template" : "%s",
    "default" : "portfolio"
  },
  description: 'Generated by kimoon',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`body`}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
